# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-04 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fact_book', '0002_auto_20160522_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
